name: label-studio:build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools pytest blinker coverage
        pip install -e .
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: init project
      run: |
        label-studio init my_project
    - name: Test with pytest
      run: |
        python -m pytest -vrP
        coverage run -m --source=label_studio pytest
        coverage report -m

